api_token: "60b334f36db720a2c3a602bade68ae438de0a76855fabd73021288d4d5265c3b"
projects:
  Sampath:
    working_directory: "/opt/Docker/Sampath/"
    deploy_command: "docker-compose up -d"
    services:
      auth-service:
        deploy_command: "docker compose up -d auth-service"
      standalone-service:
        working_directory: "/tmp/deployments/my-project/standalone-service"
        deploy_command: "./deploy.sh"
